server:
  port: 8821
spring:
  #JSP
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    name: lmrd
    #url: jdbc:mysql://rm-2zeen9i09ic74d6bcfo.mysql.rds.aliyuncs.com/mep_tax
    #username: mepuser
    #password: 2018!1QWE
    url: jdbc:mysql://localhost:3306/lmrd?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: MySQLRoot123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
#  thymeleaf:
#    cache: false
#    ## 检查模板是否存在，然后再呈现
#    check-template-location: true
#    #Content-Type值
#    #content-type: text/html
#    #启用MVC Thymeleaf视图分辨率
#    enabled: true
#    ## 应该从解决方案中排除的视图名称的逗号分隔列表
#    ##spring.thymeleaf.excluded-view-names=
#    #模板编码
#    mode: LEGACYHTML5
#    # 在构建URL时预先查看名称的前缀
#    prefix: classpath:/templates/
#    # 构建URL时附加查看名称的后缀.
#    suffix: .html
# 链中模板解析器的顺序
#spring.thymeleaf.template-resolver-order= o
# 可以解析的视图名称的逗号分隔列表
#spring.thymeleaf.view-names=
#thymeleaf end

#debug: true

#logging:
#  level:
#    com.dhc.dao: DEBUG


mybatis:
  type-aliases-package: com.lmrd.entity
  configLocation: classpath:mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml
  check-config-location: true



